baseURL = "/"
languageCode = "en-us"
title = "<Syllabus>"
languageLang = "en"
sectionPagesMenu = "main"
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]

[params]
description = "A free and open source web development programme."
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/syllabus/"
tree = "https://github.com/CodeYourFuture/syllabus/tree/main/"
edit = "https://github.com/CodeYourFuture/syllabus/edit/main/"
root = "syllabus"
orgapi = "https://api.github.com/repos/CodeYourFuture/"

hero = "/static/pictures/illos/candy-robots.webp"
card = "/static/pictures/illos/robots-milkshakes-macbooks.webp"


[markup]
[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true

disableKinds = ["taxonomy", "term"]
[taxonomies]
series = "versions"
